### ISSUE TITLE
Can't import recipes from BeerSmith 2 (.bsmx files)

### ISSUE THREAD

**Issue by leandrocosta** [zokipirlo/HapiBrew-Android#3]
Error message is: Error importing recipe: ...

**Comment by zokipirlo** [comment]
Beersmith file (bsmx) is not supported, only beerxml (xml). Does have this format any advantages over beerxml?

**Comment by leandrocosta** [comment]
Sorry, I thought BeerSmith format was beerxml, but I've just figured out I should export recipes "as beerxml" if I want to import them into HapiBrew.
